packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  '@node-rs/argon2': true
  sharp: true
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - '@node-rs/argon2'
  - sharp
